### ISSUE TITLE
Clicking an empty save slot then pressing escape on pause screen crashes game

### ISSUE THREAD

**Issue by VagishVela** [VagishVela/project-pygames#43]
```

```
Traceback (most recent call last):
  File "/Users/user/Projects/project-pygames/main.py", line 12, in <module>
    main()
  File "/Users/user/Projects/project-pygames/main.py", line 8, in main
    game.main()
  File "/Users/user/Projects/project-pygames/game/__main__.py", line 11, in main
    game.run()
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 142, in run
    self._handle_events()
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 121, in _handle_events
    self.events.run()
  File "/Users/user/Projects/project-pygames/game/utils/eventhandler.py", line 41, in run
    self.invoke(key, e)
  File "/Users/user/Projects/project-pygames/game/utils/eventhandler.py", line 31, in invoke
    func(event)
  File "/Users/user/Projects/project-pygames/game/views/start.py", line 40, in on_click
    self.change_views("menu.Menu", caption="Menu")
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 226, in change_views
    next_view.run(_spl_args or None)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 146, in run
    self.on_update()
  File "/Users/user/Projects/project-pygames/game/views/menu.py", line 42, in on_update
    b.update()
  File "/Users/user/Projects/project-pygames/game/utils/button.py", line 61, in update
    self.on_click()
  File "/Users/user/Projects/project-pygames/game/utils/button.py", line 124, in _change_to_view
    self.view.change_views(self.link_to_path)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 226, in change_views
    next_view.run(_spl_args or None)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 142, in run
    self._handle_events()
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 121, in _handle_events
    self.events.run()
  File "/Users/user/Projects/project-pygames/game/utils/eventhandler.py", line 41, in run
    self.invoke(key, e)
  File "/Users/user/Projects/project-pygames/game/utils/eventhandler.py", line 31, in invoke
    func(event)
  File "/Users/user/Projects/project-pygames/game/views/slots.py", line 79, in on_keydown
    self.change_views(self.escape_to)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 226, in change_views
    next_view.run(_spl_args or None)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 146, in run
    self.on_update()
  File "/Users/user/Projects/project-pygames/game/views/menu.py", line 42, in on_update
    b.update()
  File "/Users/user/Projects/project-pygames/game/utils/button.py", line 61, in update
    self.on_click()
  File "/Users/user/Projects/project-pygames/game/utils/button.py", line 124, in _change_to_view
    self.view.change_views(self.link_to_path)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 226, in change_views
    next_view.run(_spl_args or None)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 146, in run
    self.on_update()
  File "/Users/user/Projects/project-pygames/game/views/slots.py", line 59, in on_update
    b.update()
  File "/Users/user/Projects/project-pygames/game/utils/button.py", line 61, in update
    self.on_click()
  File "/Users/user/Projects/project-pygames/game/utils/button.py", line 124, in _change_to_view
    self.view.change_views(self.link_to_path)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 226, in change_views
    next_view.run(_spl_args or None)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 142, in run
    self._handle_events()
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 121, in _handle_events
    self.events.run()
  File "/Users/user/Projects/project-pygames/game/utils/eventhandler.py", line 41, in run
    self.invoke(key, e)
  File "/Users/user/Projects/project-pygames/game/utils/eventhandler.py", line 31, in invoke
    func(event)
  File "/Users/user/Projects/project-pygames/game/views/map.py", line 114, in on_keydown
    self.change_views('pause.Pause#{"escape":"map.Map"}', caption="Paused")
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 226, in change_views
    next_view.run(_spl_args or None)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 146, in run
    self.on_update()
  File "/Users/user/Projects/project-pygames/game/views/pause.py", line 55, in on_update
    b.update()
  File "/Users/user/Projects/project-pygames/game/utils/button.py", line 61, in update
    self.on_click()
  File "/Users/user/Projects/project-pygames/game/utils/button.py", line 124, in _change_to_view
    self.view.change_views(self.link_to_path)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 226, in change_views
    next_view.run(_spl_args or None)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 142, in run
    self._handle_events()
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 121, in _handle_events
    self.events.run()
  File "/Users/user/Projects/project-pygames/game/utils/eventhandler.py", line 41, in run
    self.invoke(key, e)
  File "/Users/user/Projects/project-pygames/game/utils/eventhandler.py", line 31, in invoke
    func(event)
  File "/Users/user/Projects/project-pygames/game/views/slots.py", line 79, in on_keydown
    self.change_views(self.escape_to)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 226, in change_views
    next_view.run(_spl_args or None)
  File "/Users/user/Projects/project-pygames/game/views/__init__.py", line 145, in run
    self.on_draw()
  File "/Users/user/Projects/project-pygames/game/views/pause.py", line 67, in on_draw
    for b in self.buttons:
TypeError: 'NoneType' object is not iterable
```
```

**Comment by ificiana** [comment]
perhaps fixed in #47
